export {default as IAdmin} from './admin.interface';
export {default as IClient} from './client.interface';
export {default as IEvent} from './event.interface';
export {default as IJob} from './job.interface';
export {default as ITroll} from './troll.interface';
export {default as INews} from './news.interface';
export {default as IBlog} from './blog.interface';
export {default as ITrollComment} from './troll.comment.interface';
export {default as ITrollLike} from './troll.like.interface';
export {default as ITrollShare} from './troll.share.interface';
export {IPolicyHandler,PolicyHandler} from './casl.interface';
